In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

In [ ]:
import os
os.chdir("/content/drive/My Drive/Colab Notebooks/Ericsson")

In [ ]:
import pandas as pd, numpy as np

path = "gapminder1.xlsx"

df_g = pd.read_excel(path, index_col=0)
df_1992 = df_g.loc[df_g["year"] == 1992]

In [ ]:
# df_empl being my big df...
pd.set_option('display.max_rows', 4)
print("Display 4 rows max:\n", df_1992, "\n")

pd.set_option('display.max_rows', None)
print("Display All rows:\n", df_1992, "\n")

Display 4 rows max:
           country continent  year  lifeExp       pop    gdpPercap
9     Afghanistan      Asia  1992   41.674  16317921   649.341395
21        Albania    Europe  1992   71.581   3326498  2497.437901
...           ...       ...   ...      ...       ...          ...
1689       Zambia    Africa  1992   46.100   8381163  1210.884633
1701     Zimbabwe    Africa  1992   60.377  10704340   693.420786

[142 rows x 6 columns]

Display All rows:
                        country continent  ...         pop     gdpPercap
9                  Afghanistan      Asia  ...    16317921    649.341395
21                     Albania    Europe  ...     3326498   2497.437901
33                     Algeria    Africa  ...    26298373   5023.216647
45                      Angola    Africa  ...     8735988   2627.845685
57                   Argentina  Americas  ...    33958947   9308.418710
69                   Australia   Oceania  ...    17481977  23424.766830
81                     Austria    Europe  ...     7914969  27042.018680
93                     Bahrain      Asia  ...      529491  19035.579170
105                 Bangladesh      Asia  ...   113704579    837.810164
117                    Belgium    Europe  ...    10045622  25575.570690
129                      Benin    Africa  ...     4981671   1191.207681
141                    Bolivia  Americas  ...     6893451   2961.699694
153     Bosnia and Herzegovina    Europe  ...     4256013   2546.781445
165                   Botswana    Africa  ...     1342614   7954.111645
177                     Brazil  Americas  ...   155975974   6950.283021
189                   Bulgaria    Europe  ...     8658506   6302.623438
201               Burkina Faso    Africa  ...     8878303    931.752773
213                    Burundi    Africa  ...     5809236    631.699878
225                   Cambodia      Asia  ...    10150094    682.303175
237                   Cameroon    Africa  ...    12467171   1793.163278
249                     Canada  Americas  ...    28523502  26342.884260
261   Central African Republic    Africa  ...     3265124    747.905525
273                       Chad    Africa  ...     6429417   1058.064300
285                      Chile  Americas  ...    13572994   7596.125964
297                      China      Asia  ...  1164970000   1655.784158
309                   Colombia  Americas  ...    34202721   5444.648617
321                    Comoros    Africa  ...      454429   1246.907370
333           Congo, Dem. Rep.    Africa  ...    41672143    457.719181
345                Congo, Rep.    Africa  ...     2409073   4016.239529
357                 Costa Rica  Americas  ...     3173216   6160.416317
369              Cote d'Ivoire    Africa  ...    12772596   1648.073791
381                    Croatia    Europe  ...     4494013   8447.794873
393                       Cuba  Americas  ...    10723260   5592.843963
405             Czech Republic    Europe  ...    10315702  14297.021220
417                    Denmark    Europe  ...     5171393  26406.739850
429                   Djibouti    Africa  ...      384156   2377.156192
441         Dominican Republic  Americas  ...     7351181   3044.214214
453                    Ecuador  Americas  ...    10748394   7103.702595
465                      Egypt    Africa  ...    59402198   3794.755195
477                El Salvador  Americas  ...     5274649   4444.231700
489          Equatorial Guinea    Africa  ...      387838   1132.055034
501                    Eritrea    Africa  ...     3668440    582.858510
513                   Ethiopia    Africa  ...    52088559    421.353465
525                    Finland    Europe  ...     5041039  20647.164990
537                     France    Europe  ...    57374179  24703.796150
549                      Gabon    Africa  ...      985739  13522.157520
561                     Gambia    Africa  ...     1025384    665.624413
573                    Germany    Europe  ...    80597764  26505.303170
585                      Ghana    Africa  ...    16278738    925.060154
597                     Greece    Europe  ...    10325429  17541.496340
609                  Guatemala  Americas  ...     8486949   4439.450840
621                     Guinea    Africa  ...     6990574    794.348438
633              Guinea-Bissau    Africa  ...     1050938    745.539871
645                      Haiti  Americas  ...     6326682   1456.309517
657                   Honduras  Americas  ...     5077347   3081.694603
669           Hong Kong, China      Asia  ...     5829696  24757.603010
681                    Hungary    Europe  ...    10348684  10535.628550
693                    Iceland    Europe  ...      259012  25144.392010
705                      India      Asia  ...   872000000   1164.406809
717                  Indonesia      Asia  ...   184816000   2383.140898
729                       Iran      Asia  ...    60397973   7235.653188
741                       Iraq      Asia  ...    17861905   3745.640687
753                    Ireland    Europe  ...     3557761  17558.815550
765                     Israel      Asia  ...     4936550  18051.522540
777                      Italy    Europe  ...    56840847  22013.644860
789                    Jamaica  Americas  ...     2378618   7404.923685
801                      Japan      Asia  ...   124329269  26824.895110
813                     Jordan      Asia  ...     3867409   3431.593647
825                      Kenya    Africa  ...    25020539   1341.921721
837           Korea, Dem. Rep.      Asia  ...    20711375   3726.063507
849                Korea, Rep.      Asia  ...    43805450  12104.278720
861                     Kuwait      Asia  ...     1418095  34932.919590
873                    Lebanon      Asia  ...     3219994   6890.806854
885                    Lesotho    Africa  ...     1803195    977.486273
897                    Liberia    Africa  ...     1912974    636.622919
909                      Libya    Africa  ...     4364501   9640.138501
921                 Madagascar    Africa  ...    12210395   1040.676190
933                     Malawi    Africa  ...    10014249    563.200014
945                   Malaysia      Asia  ...    18319502   7277.912802
957                       Mali    Africa  ...     8416215    739.014375
969                 Mauritania    Africa  ...     2119465   1361.369784
981                  Mauritius    Africa  ...     1096202   6058.253846
993                     Mexico  Americas  ...    88111030   9472.384295
1005                  Mongolia      Asia  ...     2312802   1785.402016
1017                Montenegro    Europe  ...      621621   7003.339037
1029                   Morocco    Africa  ...    25798239   2948.047252
1041                Mozambique    Africa  ...    13160731    410.896824
1053                   Myanmar      Asia  ...    40546538    347.000000
1065                   Namibia    Africa  ...     1554253   3804.537999
1077                     Nepal      Asia  ...    20326209    897.740360
1089               Netherlands    Europe  ...    15174244  26790.949610
1101               New Zealand   Oceania  ...     3437674  18363.324940
1113                 Nicaragua  Americas  ...     4017939   2170.151724
1125                     Niger    Africa  ...     8392818    581.182725
1137                   Nigeria    Africa  ...    93364244   1619.848217
1149                    Norway    Europe  ...     4286357  33965.661150
1161                      Oman      Asia  ...     1915208  18616.706910
1173                  Pakistan      Asia  ...   120065004   1971.829464
1185                    Panama  Americas  ...     2484997   6618.743050
1197                  Paraguay  Americas  ...     4483945   4196.411078
1209                      Peru  Americas  ...    22430449   4446.380924
1221               Philippines      Asia  ...    67185766   2279.324017
1233                    Poland    Europe  ...    38370697   7738.881247
1245                  Portugal    Europe  ...     9927680  16207.266630
1257               Puerto Rico  Americas  ...     3585176  14641.587110
1269                   Reunion    Africa  ...      622191   6101.255823
1281                   Romania    Europe  ...    22797027   6598.409903
1293                    Rwanda    Africa  ...     7290203    737.068595
1305     Sao Tome and Principe    Africa  ...      125911   1428.777814
1317              Saudi Arabia      Asia  ...    16945857  24841.617770
1329                   Senegal    Africa  ...     8307920   1367.899369
1341                    Serbia    Europe  ...     9826397   9325.068238
1353              Sierra Leone    Africa  ...     4260884   1068.696278
1365                 Singapore      Asia  ...     3235865  24769.891200
1377           Slovak Republic    Europe  ...     5302888   9498.467723
1389                  Slovenia    Europe  ...     1999210  14214.716810
1401                   Somalia    Africa  ...     6099799    926.960296
1413              South Africa    Africa  ...    39964159   7225.069258
1425                     Spain    Europe  ...    39549438  18603.064520
1437                 Sri Lanka      Asia  ...    17587060   2153.739222
1449                     Sudan    Africa  ...    28227588   1492.197043
1461                 Swaziland    Africa  ...      962344   3553.022400
1473                    Sweden    Europe  ...     8718867  23880.016830
1485               Switzerland    Europe  ...     6995447  31871.530300
1497                     Syria      Asia  ...    13219062   3340.542768
1509                    Taiwan      Asia  ...    20686918  15215.657900
1521                  Tanzania    Africa  ...    26605473    825.682454
1533                  Thailand      Asia  ...    56667095   4616.896545
1545                      Togo    Africa  ...     3747553   1034.298904
1557       Trinidad and Tobago  Americas  ...     1183669   7370.990932
1569                   Tunisia    Africa  ...     8523077   4332.720164
1581                    Turkey    Europe  ...    58179144   5678.348271
1593                    Uganda    Africa  ...    18252190    644.170797
1605            United Kingdom    Europe  ...    57866349  22705.092540
1617             United States  Americas  ...   256894189  32003.932240
1629                   Uruguay  Americas  ...     3149262   8137.004775
1641                 Venezuela  Americas  ...    20265563  10733.926310
1653                   Vietnam      Asia  ...    69940728    989.023149
1665        West Bank and Gaza      Asia  ...     2104779   6017.654756
1677               Yemen, Rep.      Asia  ...    13367997   1879.496673
1689                    Zambia    Africa  ...     8381163   1210.884633
1701                  Zimbabwe    Africa  ...    10704340    693.420786

[142 rows x 6 columns]